Removed NetService.ProcessSegment by inlining the NetManager call.
CitiesSkylinesMods/TMPE pull request #1023
Opened 2020-10-30 01:43 UTC by DaEgi01

Please double check that I always passed the correct segmentId to the NetManager and that the following segment reference is the one that is used further on.

2020-10-30 01:57 UTC, kvakvs reviewed
Looks good, as long as the changes are equivalent to the old code

2020-10-30 11:35 UTC, kianzarrin commented
@DaEgi01 wouldn't it have been better to just use `segmentID.ToSegment()` from the extension class called `Shortcuts` ?
is this code in the performance critical part of the code?

2020-10-31 19:16 UTC, DaEgi01 commented
> Looks good, as long as the changes are equivalent to the old code

It should be. I checked three times but I m not perfect.
So it would be great if another pair of eyes could verify it.

> @DaEgi01 wouldn't it have been better to just use `segmentID.ToSegment()` from the extension class called `Shortcuts` ?
> is this code in the performance critical part of the code?

Probably, I forgot about ToSegment.
The original method that I replaced did not use the ToSegment extension method.
I tried to just do the conversion mechanically without any extras such that I don't introduce any errors.
But I did a cleanup here and there - for example I inlined the previously separate declaration and initialization of some variables, which was necessary before but not after - less assignments is also better :)
Regarding perf, my first assumption would be that the ToSegment() method is probably simple enough that it will be inlined during compilation. I should double check that.
If not, we can still try with the aggresive inlining attribute.
I ll check that.

2020-11-04 03:05 UTC, DaEgi01 commented
Ok, moved the code to "ToSegment()".
I checked if it is inlined after compilation, and it is not.
Also `[MethodImpl(MethodImplOptions.AggressiveInlining)]` seems to be a .net 4.5+ thing, so we are out of luck here.
I would still keep using ToSegment() since its handy and the perf cost of a static method call is not high.
Its significantly better than the closure before, that is for sure.
Also Singleton<NetManager>.instance.m_segments.m_buffer is already dereferenced in _segBuffer so its probably even a little faster (maybe that is the reason why it can't be inlined!?).

2020-11-04 04:16 UTC, FireController1847 approved these changes
LGTM 👍

2020-11-04 21:13 UTC, krzychu124 requested changes

2020-11-04 21:13 UTC, krzychu124 commented on TLM/TLM/Manager/Impl/ExtVehicleManager.cs
> +            var transitNodeId1 = startNode
Hmm, I believe there is a method in `NetSegment`  returning start/end node 🤔

2020-11-05 18:29 UTC, krzychu124 commented on TLM/TLM/Manager/Impl/ExtVehicleManager.cs
> +            var transitNodeId1 = startNode
Ok, nvm, I couldn't find it... 😅

2020-11-05 18:32 UTC, krzychu124 approved these changes
Since I couldn't find method from requested I added, I approve PR. If you want to implement it as extension method, go ahead :)

2020-11-06 11:53 UTC, merged