Preparations for SpeedLimits: U interface and texture loading changed
CitiesSkylinesMods/TMPE pull request #1044
Opened 2020-12-22 03:31 UTC by kvakvs

* Texture and texture-atlas loading changed: now you can define desired texture size
* RoadDefaults textures commented out will be added and loaded in the following update

2020-12-26 02:17 UTC, krzychu124 approved these changes
Looks good to me 👍

2021-01-29 06:05 UTC, kianzarrin commented on TLM/TLM/U/AtlasBuilder.cs
> +            if (!System.Object.ReferenceEquals(foundAtlas, UIView.GetAView().defaultAtlas)) {
I can understand that there is the issue of confusing this with unity object but if you simply use object. that would work too.
Just a side note. no need to fix.

2021-01-29 06:24 UTC, kianzarrin commented
Window has opacity but components have transparency ... a bit inconsistent. I understand fixing this might need a lot of code changes and might be out of the scope of this review. so no pressure.
![image](https://user-images.githubusercontent.com/26344691/106239337-1caa0980-620b-11eb-984f-65c24cfbd075.png)

2021-01-29 06:28 UTC, kianzarrin commented
I have selected the parking tool. but no parking overlay 
![image](https://user-images.githubusercontent.com/26344691/106239803-e1f4a100-620b-11eb-8b9e-21083380abca.png)

2021-01-29 06:41 UTC, kianzarrin requested changes
see https://github.com/CitiesSkylinesMods/TMPE/pull/1044#issuecomment-769607015

2021-01-29 10:47 UTC, krzychu124 commented
> I have selected the parking tool. but no parking overlay
> ![image](https://user-images.githubusercontent.com/26344691/106239803-e1f4a100-620b-11eb-8b9e-21083380abca.png)
> EDIT: once I rotate the screen the parking overlay reappears
> ![image](https://user-images.githubusercontent.com/26344691/106239870-fdf84280-620b-11eb-8375-37df0d57dbcc.png)
> 
> This is sometimes reproducible and sometimes not. So for example:
> 
> * switch to speed tool -> switch to parking tool -> parking sprites are visible
> * switch to Vehicle restriction tool -> exit Vehicle restriction tool -> switch to parking tool -> parking sprites not visible until I rotate the screen.

Pretty old bug, introduced with camera position caching mechanism.

2021-01-29 14:24 UTC, kvakvs commented
@kianzarrin For opacity/transparency, the work you mentioned is already done. I store the opacity/transparency in the same float value, in a struct. Its probably the UI inconsistency here?
@krzychu124 The bug is not introduced in this branch? Happy to fix it, but not all problems at once :)

2021-01-29 16:04 UTC, kianzarrin approved these changes
In that case looks good to me

2021-01-30 12:46 UTC, krzychu124 commented
@kvakvs I think it was introduced when you've added camera transform cache thingy to speed up rendering of overlays long time ago. If you don't move camera and switch tool with overlays they won't show up until you move it a little bit

2021-01-30 12:48 UTC, kvakvs commented
I am slowly refactoring overlays into separate modules one per tool.
Can have this as a TODO item in the final Pull request for Speed Limits if its urgent, or as some high prio bug to do after it

2021-01-30 14:12 UTC, krzychu124 commented
Yeah I'm waiting for speed limits refactor to begin some work on performance improvements. I plan to improve TM:PE to be able to run it with Unity profiler. I'm not sure yet what changes are necessary to make it work and not crash at start

2021-01-31 13:31 UTC, merged