Improved pathfinding lifecycle
CitiesSkylinesMods/TMPE pull request #1145
Opened 2021-08-07 02:01 UTC by krzychu124

### Before the change
Upon loading a savegame game could request recalculation of public transport paths before `CustomPathManager` became fully initialized with all required Harmony patches, which most of the times resulted in multiple `NullReference` exceptions right after save game has been loaded. That's because custom manager was null(not yet replaced) or not all `PathManager.CreatePath()` calls has been correctly redirected in time (patched too late).
The other issue were in `PathManager.WaitingForPaths()` when game was exiting to main menu or reloading the savegame. That could trigger multiple exceptions from partially restored vanilla pathfinding (instance was restored but compatibility patches were still applied)

### Changes
- rewritten execution flow of instantiating, destroying and managing TM:PE `CustomPathManager` 
- added separate `harmony_id` for manual application of PF related patches,
- Path-finding related patches are manually applied when `CustomPathManager` is instantiated and removed on destroy,
- added short documentation for methods, fixed few typos,
___
Above improvements should completely eliminate `NullReference` exceptions after load, reload the savegame or hot-reloading. 
Similar problem (TMPE patched only partially) might affect also the Stable build -> I remember multiple user reports about disconnected public transport lines right after savegame load(before user started simulation) - this change should fix that issue.

Build:

2021-08-07 03:00 UTC, kvakvs reviewed
Harmony and mod startup is the dark magic to me
And functions with 300 arguments also create uncomfortable feeling :)
Otherwise the code looks good

2021-08-21 11:46 UTC, DaEgi01 approved these changes

2021-08-24 05:23 UTC, kianzarrin requested changes

2021-08-24 05:23 UTC, kianzarrin commented on TLM/TLM/Lifecycle/Patcher.cs
> +            fail = !PatchAll(typeof(CustomPathFindPatchAttribute));;
patching with normal harmony id. PatchAll needs to accept harmony id.

2021-08-24 10:37 UTC, DaEgi01 approved these changes

2021-08-25 07:47 UTC, kianzarrin approved these changes
👍

2021-08-25 12:16 UTC, merged