Simplify UI scaler
CitiesSkylinesMods/TMPE pull request #1157
Opened 2021-09-04 08:53 UTC by kianzarrin

2021-09-04 09:11 UTC, DaEgi01 requested changes

2021-09-04 09:11 UTC, DaEgi01 commented on TLM/TLM/U/UIScaler.cs
> +        private static float BaseResolutionX => UIView.GetAView().GetScreenResolution().x;
I'd reduce GetAView() calls to a minimum.
Call it once and cache it.
The method searches every time for the first UIView even though the value never changes.
Also the method is implemented via LINQ and will cause heap allocations each time.

2021-09-04 09:48 UTC, kvakvs approved these changes
Renaming config option will reset scale for everyone.

2021-09-04 12:23 UTC, DaEgi01 commented
> Renaming config option will reset scale for everyone.

I see, how do we handle that?
1. we don't care about the user?
2. we don't care about the code?
:D

2021-09-04 12:45 UTC, kvakvs commented
> I see, how do we handle that?
>     1. we don't care about the user?
>     2. we don't care about the code?

Reasonable default

or keep old variable, give new variable default -1 for example, and if it is -1, we migrate value to new on the first load. This migration code can be removed in the next release.

2021-09-04 13:49 UTC, DaEgi01 commented
> > I see, how do we handle that?
> > 1. we don't care about the user?
> > 2. we don't care about the code?
> 
> Reasonable default for example 100% zoom
> 
> or keep old variable, give new variable default -1 for example, and if it is -1, we migrate value to new on the first load. This migration code can be removed in the next release.

To be honest, in that case I'd probably leave the variable name as is since its too much hastle for too little gain. I did not consider that when I proposed to rename the variable. But your solution also sounds fine.

2021-09-04 22:41 UTC, DaEgi01 approved these changes

2021-09-05 16:06 UTC, DaEgi01 approved these changes

2021-09-06 21:03 UTC, krzychu124 approved these changes
👍

2021-09-08 05:20 UTC, merged