routing detector: detail all routings when no target lane
CitiesSkylinesMods/TMPE pull request #1549
Opened 2022-04-26 07:02 UTC by kianzarrin

![image](https://user-images.githubusercontent.com/26344691/165240638-02df705a-9d99-40b7-a1ea-06d2d7467ee5.png)
when hovering/selecting source lane, all target lanes are highlighted but the hint box did not list them. In this PR I fixed this.

2022-04-26 16:09 UTC, aubergine10 approved these changes
LGTM 👍 

I hope one day this sort of thing finds its way in to main lane arrows/connnectors tools to help users understand exactly where each lane is leading to, including any lanes they haven't yet customised.

2022-04-26 20:29 UTC, krzychu124 requested changes
No icon -> files not loaded in `FullDebug` target:

![image](https://user-images.githubusercontent.com/19638970/165385092-1f06ee62-87cb-4f80-bfdf-2c8ceb0f6d8f.png)

Exception not fixed: https://github.com/CitiesSkylinesMods/TMPE/pull/1534#issuecomment-1101864122

Other than above, it works. I would add info about hovered lane since it shows ids if nothing is hovered. Maybe also the id of selected lane (might be useful for debugging with log file)

2022-04-27 00:05 UTC, kianzarrin commented
id of the selected lane can be detected using network detective tool.

2022-04-27 09:33 UTC, krzychu124 approved these changes

2022-04-27 12:34 UTC, merged