spell-check
CitiesSkylinesMods/TMPE pull request #1672
Opened 2022-10-09 19:50 UTC by kianzarrin

2022-10-09 20:58 UTC, kvakvs approved these changes

2022-10-10 06:30 UTC, chameleon-tbn approved these changes
Lgtm

2022-10-10 19:33 UTC, krzychu124 requested changes

2022-10-10 19:33 UTC, krzychu124 commented on TLM/TLM/Patch/_VehicleAI/UpdatePathTargetPositionsPatch.cs
> +                                "Next path position needs to be calculated. Used triple-calculation. " +
That additional "next" is important here. Means the next after current next = 2nd next position

2022-10-11 10:01 UTC, krzychu124 approved these changes

2022-10-11 20:03 UTC, merged